//
//  MainModels.swift
//  HomeStore
//
//  Created by Vlad Ralovich on 22.08.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Main
{
    // MARK: Use cases
    
    enum Something
    {
        struct Request
        {
            enum RequestType {
                case load
            }
        }
        struct Response
        {
            enum ResponseType {
                case loaded
            }
        }
        struct ViewModel
        {
            enum ViewModelType {
                case showData
            }
        }
    }
}
