//
//  MainInteractor.swift
//  HomeStore
//
//  Created by Vlad Ralovich on 22.08.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MainBusinessLogic {
    func doReuest(request: Main.Something.Request.RequestType)
}

protocol MainDataStore {
  //var name: String { get set }
}

class MainInteractor: MainBusinessLogic, MainDataStore {
  var presenter: MainPresentationLogic?
  var worker: MainWorker?
  //var name: String = ""
  
  // MARK: Do something
  
    func doReuest(request: Main.Something.Request.RequestType) {
//    worker = MainWorker()
//    worker?.doSomeWork()
        NetworkLayer.loadAllData(urlString: "https://run.mocky.io/v3/654bd15e-b121-49ba-a588-960956b15175") { [weak self] data in
            self?.presenter?.presentResponse(response: .loaded(data))
        }
  }
}
